import {StyleSheet, Dimensions, Platform} from 'react-native';
let width = Dimensions.get('window').width;
const {height: SCREEN_HEIGHT} = Dimensions.get('window');
const IS_IPHONE_X = SCREEN_HEIGHT === 812 || SCREEN_HEIGHT === 896;
const STATUS_BAR_HEIGHT = Platform.OS === 'ios' ? (IS_IPHONE_X ? 44 : 20) : 0;
const HEADER_HEIGHT = Platform.OS === 'ios' ? (IS_IPHONE_X ? 88 : 64) : 64;
const NAV_BAR_HEIGHT = HEADER_HEIGHT - STATUS_BAR_HEIGHT;

export const styles = StyleSheet.create({
  container: {
    marginHorizontal: 20,
  },
  container1: {
    flex: 1,
  },
  containerMedia: {
    flexDirection: 'row',
    marginTop: 12,
    marginRight: 20,
    justifyContent: 'flex-end',
  },
  containerUpdateModal: {backgroundColor: '#f0f7fffc'},
  containerKategori: {
    marginHorizontal: 8,
    marginTop: 18,
  },
  containerLaporan: {
    marginHorizontal: 18,
    marginTop: 18,
    alignSelf: 'flex-end',
  },
  containerStruk: {
    // marginHorizontal: 8,
    marginTop: 18,
    flexDirection: 'row',
  },
  containerKategori1: {
    backgroundColor: '#fff',
    height: 60,
    shadowOffset: {width: 0.5, height: 0.5},
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
    justifyContent: 'center',
  },
  containerLaporan1: {
    backgroundColor: '#fff',
    height: 80,
    shadowOffset: {width: 0.5, height: 0.5},
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
    justifyContent: 'center',
    marginTop: 10,
    width: 260,
  },
  containerLaporan2: {
    backgroundColor: '#fff',
    height: 59,
    shadowOffset: {width: 0.5, height: 0.5},
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
    justifyContent: 'center',
    marginTop: 10,
    width: 260,
  },
  containerLaporan3: {
    backgroundColor: '#fff',
    height: 76,
    shadowOffset: {width: 0.5, height: 0.5},
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
    justifyContent: 'center',
    marginTop: 10,
    width: 260,
  },
  containerChart: {
    backgroundColor: 'green',
    height: 77,
    shadowOffset: {width: 0.4, height: 0.4},
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    justifyContent: 'center',
    marginTop: 10,
    width: 40,
    alignItems: 'center',
  },
  containerChart1: {
    backgroundColor: 'green',
    height: 60,
    shadowOffset: {width: 0.5, height: 0.5},
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
    justifyContent: 'center',
    marginTop: 10,
    width: 40,
    alignItems: 'center',
  },
  containerKategori2: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    height: 220,
    shadowOffset: {width: 0.5, height: 0.5},
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
    alignItems: 'center',
  },
  line: {fontSize: 24, color: 'grey', alignSelf: 'center'},
  onlyFlex1: {flex: 1},
  onlyRow: {flexDirection: 'row'},
  Struk1: {
    marginHorizontal: 26,
    marginTop: 8,
    alignItems: 'center',
  },
  fontLaporan: {
    fontSize: 22,
    fontWeight: 'bold',
    marginLeft: 20,
    color: 'grey',
  },
  fontLaporan1: {color: 'grey', marginLeft: 20},
  fontLaporan2: {color: 'grey', alignSelf: 'center', fontStyle: 'italic'},
  fontHeaderLaporan: {
    marginTop: 20,
    fontSize: 18,
    fontWeight: 'bold',
  },
  chart: {width: 26, height: 26, tintColor: 'white'},

  Struk2: {
    fontSize: 20,
    fontWeight: '900',
    textDecorationLine: 'underline',
  },
  AlignCenter: {alignItems: 'center'},
  Struk3: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 14,
  },
  Struk4: {marginHorizontal: 26, marginTop: 8},
  Struk5: {flexDirection: 'row', justifyContent: 'space-between'},
  Struk6: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  fontStruk: {fontSize: 14, color: 'grey'},
  fontStruk1: {fontSize: 9, color: 'grey'},
  fontStruk2: {fontSize: 17, fontWeight: '900', color: 'black'},
  fontStruk3: {fontSize: 14, fontWeight: 'bold', color: 'black'},
  fontStruk4: {fontSize: 13, fontWeight: '900', color: 'black'},

  planColor: {backgroundColor: '#f0f7fffc'},
  strukContainer: {backgroundColor: 'white', flex: 1, borderRadius: 6},
  flex1: {
    flex: 1,
  },
  loading: {
    width: 100,
    height: 100,
    alignSelf: 'center',
    marginTop: 100,
  },
  isLoading: {backgroundColor: '#f0f7fffc', flex: 1},
  fontIntro: {
    fontWeight: 'bold',
    fontSize: 30,
    color: '#ffd700',
    alignSelf: 'center',
    marginTop: 24,
    marginBottom: 60,
  },
  fontHeader: {
    fontWeight: 'bold',
    fontSize: 25,
    color: 'white',
    marginLeft: 20,
  },
  fontHeader1: {
    fontWeight: 'bold',
    fontSize: 25,
    color: 'white',
    marginTop: 26,
    marginLeft: 18,
  },
  fontHeader2: {
    fontWeight: 'bold',
    fontSize: 16,
    color: 'white',
    marginTop: 180,
    alignSelf: 'center',
    backgroundColor: '#86c1d5',
    width: 200,
    textAlign: 'center',
    borderRadius: 4,
    height: 26,
  },
  fontHeader3: {
    fontWeight: 'bold',
    fontSize: 18,
    color: 'white',
    alignSelf: 'center',
    marginLeft: 18,
    marginTop: 24,
  },
  fontHeader4: {
    fontWeight: 'bold',
    fontSize: 18,
    color: 'white',
    marginTop: 40,

    // marginRight: 18,
  },
  fontHeader5: {
    fontWeight: 'bold',
    fontSize: 18,
    marginTop: 40,
    color: 'black',
    // marginRight: 18,
  },
  logo: {
    height: 200,
    width: 200,
    alignSelf: 'center',
    marginTop: 70,
  },
  splashscreen: {
    height: 180,
    width: 180,
    alignSelf: 'center',
    marginTop: 180,
  },
  dev: {
    alignSelf: 'center',
  },
  bg: {
    marginTop: 80,
  },
  marginLeft40: {
    marginLeft: 40,
  },
  iconStruk: {
    marginTop: 18,
    marginLeft: 12,
    flexDirection: 'row',
  },
  marginLeft26: {
    marginLeft: 26,
  },
  marginLeft14: {
    marginLeft: 14,
  },
  fontEmail1: {
    marginTop: 100,
    color: '#7b889d',
  },
  fontEmail: {
    marginTop: 60,
    color: '#7b889d',
  },
  fontInput: {
    backgroundColor: 'white',
    borderRadius: 6,
  },
  fontInputStruk: {
    // backgroundColor: 'white',
    borderRadius: 6,
    width: 280,
    fontSize: 20,
  },
  fontInputStruk1: {alignSelf: 'center', fontSize: 18, marginRight: 8},
  fontUnderStruk: {alignSelf: 'center', color: 'grey'},
  fontInput1: {
    backgroundColor: 'green',
    borderRadius: 6,
    width: 200,
    height: 40,
    marginTop: 20,
  },
  fontPassword: {
    marginTop: 25,
    color: '#7b889d',
  },
  formInputData: {
    width: 320,
    borderColor: 'black',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  fontInputPass: {
    width: 200,
  },
  eyePassword: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 6,
  },
  iconDownload: {height: 24, width: 24, marginRight: 6},
  iconShare: {height: 24, width: 24},

  iconEdit: {height: 26, width: 26, marginBottom: 20},
  iconEdit1: {
    height: 26,
    width: 26,
    marginBottom: 18,
    marginLeft: 140,
    marginTop: 10,
  },
  iconErased: {height: 28, width: 28},
  iconErased1: {height: 28, width: 28, marginLeft: 18, marginTop: 10},
  iconBoard1: {
    width: 46,
    height: 46,
    tintColor: '#1d99ed',
  },
  iconBoard2: {
    width: 46,
    height: 46,
    tintColor: '#f98585',
  },
  iconBoard3: {
    width: 46,
    height: 46,
    tintColor: '#1f9ff4',
  },
  iconBoard4: {
    width: 46,
    height: 46,
    tintColor: '#074864',
  },
  iconBoard5: {
    width: 46,
    height: 46,
  },
  iconInput: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 6,
  },

  iconinput1: {
    width: 25,
    height: 15,
    marginLeft: 6,
  },
  iconinput2: {
    width: 25,
    height: 25,
  },
  iconInput3: {
    // justifyContent: 'center',
    flex: 1,
    backgroundColor: '#f0f7fffc',
  },
  iconInput4: {
    backgroundColor: 'white',
    flex: 1,
    marginHorizontal: 16,
    marginTop: 18,
    borderRadius: 6,
  },
  iconInput5: {
    backgroundColor: 'white',
    flex: 1,
    marginHorizontal: 12,
    marginTop: 18,
    borderRadius: 8,
  },
  totalStruk: {
    marginHorizontal: 18,
    marginTop: 100,
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    marginBottom: 10,
  },
  fontTotal: {fontWeight: 'bold', fontSize: 15},
  fontTotal1: {
    color: 'grey',
    fontSize: 16,
  },
  viewInputStruk: {
    flexDirection: 'row',
    marginHorizontal: 22,
    marginTop: 40,
  },
  viewInputStruk1: {flexDirection: 'row', marginHorizontal: 22},
  eye: {
    // padding: 10,
    width: 25,
    height: 15,
    marginLeft: 55,
  },
  Signout: {height: 26, width: 26, tintColor: 'deepskyblue'},
  viewSignout: {
    alignItems: 'flex-end',
    marginHorizontal: 20,
    marginTop: 38,
  },
  viewButtonAtas: {
    flex: 1,
    flexDirection: 'column-reverse',
    zIndex: 100,
    marginTop: -500,
  },
  viewButton: {
    width: width,
    // height: 200,
    backgroundColor: 'red',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    position: 'absolute',
    flex: 1,
  },
  buttonIntro: {
    backgroundColor: '#e6c616',
    width: 260,
    height: 60,
    borderRadius: 6,
    alignSelf: 'center',
    marginBottom: 20,
    justifyContent: 'center',
  },
  button: {
    backgroundColor: '#e6c616',
    width: 260,
    height: 60,
    borderRadius: 6,
    alignSelf: 'center',
    marginTop: 40,
    justifyContent: 'center',
  },
  buttonScan: {
    backgroundColor: '#e6c616',
    width: 260,
    height: 50,
    borderRadius: 6,
    alignSelf: 'center',
    marginTop: 40,
    justifyContent: 'center',
  },
  buttonText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
  },
  buttonTextScan: {
    color: 'white',
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
  },
  buttonText1: {
    color: 'white',
    textAlign: 'center',
    fontSize: 14,
    fontWeight: 'bold',
  },
  fontForgetPass: {
    color: 'black',
    alignSelf: 'center',
    marginTop: 15,
    fontSize: 14,
    fontWeight: '900',
  },
  fontloginAnother: {
    alignSelf: 'center',
    marginTop: 25,
    fontSize: 14,
    fontWeight: 'bold',
  },
  fontIconHome: {
    color: '#0378d8',
    fontWeight: 'bold',
    fontSize: 16,
    marginTop: 18,
  },
  fontIconHome1: {
    color: '#0378d8',
    fontWeight: 'bold',
    fontSize: 14,
    marginTop: 8,
  },

  textSignUp: {
    color: '#278d11',
  },

  headBarIcon: {
    width: 30,
  },
  barIcon: {
    width: 17,
    height: 17,
  },
  iconBack: {
    height: 24,
    width: 24,
    tintColor: 'white',
    marginLeft: 18,
    marginTop: 26,
  },
  noDataIcon: {
    height: 56,
    width: 56,
  },
  iconHeaderHome: {
    height: 50,
    width: 50,
    marginLeft: 20,
    marginTop: 50,
    marginRight: 20,
  },
  iconHeaderHome1: {
    height: 56,
    width: 56,
    marginLeft: 20,
    marginTop: 34,
  },
  iconItem: {
    height: 60,
    width: 60,
    marginLeft: 10,
  },
  iconItem1: {
    height: 80,
    width: 80,
    marginLeft: 10,
  },
  iconSetting: {height: 20, width: 20},

  viewiconListSampah: {
    backgroundColor: 'white',
    height: 160,
    width: 140,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  viewiconListSampah1: {
    width: 80,
    height: 80,
    backgroundColor: '#f0f7fffc',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  board: {
    width: width,
    marginTop: -10,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    backgroundColor: '#f0f7fffc',
    flex: 1,
  },
  flexDirectionRow: {
    flexDirection: 'row',
    marginHorizontal: 30,
    marginTop: 60,
    justifyContent: 'space-between',
  },
  HeaderComponentKasir: {
    width: width,
    height: 130,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  HeaderComponent: {
    width: width,
    height: 140,
  },
  HeaderComponent1: {
    width: width,
    height: 80,
    flexDirection: 'row',
    alignItems: 'center',
  },
  HeaderComponentHome: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  Header: {
    justifyContent: 'center',

    width: width,
    height: 140,
    borderBottomRightRadius: 180,
  },
  HeaderHomeChild: {
    marginTop: 32,
    marginBottom: 20,
  },
  HeaderHomeChild2: {
    marginTop: 20,
    flexDirection: 'row',
    flex: 1,
    flexBasis: '100%',
  },
  fontInputData: {
    marginTop: 20,
    fontSize: 16,
    color: '#242323',
  },

  fontKategori: {fontSize: 14, fontWeight: 'bold', marginLeft: 20},
  fontKategori1: {
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 20,
    color: 'grey',
  },
  fontKategori2: {
    fontSize: 14,
    // fontWeight: 'bold',
    color: 'grey',
    fontStyle: 'italic',
  },
  fontKategori3: {
    fontSize: 16,
    // fontWeight: 'bold',
    marginLeft: 20,
    color: 'grey',
    fontStyle: 'italic',
  },
  fontKategori4: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 20,
    fontStyle: 'italic',
  },
  fontBody: {
    color: '#B0B0B0',
    marginTop: 15,
  },
  fontBody1: {
    color: '#7b889d',
    marginTop: 28,
    alignSelf: 'center',
    textAlign: 'center',
    fontSize: 16,
  },
  fontBody2: {
    color: '#7b889d',
    fontSize: 13,
    marginTop: 6,
  },
  fontNameHeader: {
    color: '#154F3F',
    alignSelf: 'center',
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 22,
    marginLeft: 20,
  },

  fontLogin: {
    color: '#278d11',
    fontWeight: 'bold',
  },

  fontInputPw: {
    backgroundColor: 'white',
    borderRadius: 6,
    width: 250,
  },

  fontTermofuse: {
    textAlign: 'center',
    fontSize: 12,
    color: '#B0B0B0',
    marginTop: 25,
  },
  marginTop30: {
    marginTop: 30,
  },
  marginTop20: {
    marginTop: 16,
  },
  marginTop150: {marginTop: 60},
  ColorWhite: {color: 'white'},
  switch: {
    flexDirection: 'row',
    marginTop: 20,
    justifyContent: 'space-between',
  },
  containerModal: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    flex: 1,
    flexDirection: 'column-reverse',
  },
  popupModal: {
    backgroundColor: '#fff',
    padding: 10,
  },
  containerOption: {
    marginHorizontal: 10,
    marginBottom: 30,
  },
  noData: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 100,
  },
  contentContainer: {
    flexGrow: 1,
  },
  navContainer: {
    height: HEADER_HEIGHT,
    marginHorizontal: 10,
  },
  statusBar: {
    height: STATUS_BAR_HEIGHT,
    backgroundColor: 'transparent',
  },
  navBar: {
    height: NAV_BAR_HEIGHT,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: 'transparent',
  },
  titleStyle: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 18,
  },
  resiBawah: {
    height: 10,
    width: 335,
    tintColor: 'grey',
    position: 'absolute',
    marginTop: 380,
  },
});
